# @Author: saitou
# @Date:   2015-12-06 19:03:22
# @Last Modified by:   saitou
# @Last Modified time: 2015-12-06 19:38:38
---
- hosts:
    localhost

  vars:
    ansible_python_interpreter: /home/saitou/venv/develop/bin/python
    os_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
    os_username: "{{ lookup('env','OS_USERNAME') }}"
    os_password: "{{ lookup('env','OS_PASSWORD') }}"
    os_project_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
    os_region_name: "{{ lookup('env','OS_REGION_NAME') }}"
    secgroups:
      - name: "handson_1214_base"
        desc: "secgroup for step-server"
        rules:
          - protocol: "icmp"
            port_range_min: -1
            port_range_max: -1
            remote_ip_prefix: "0.0.0.0/0"
          - protocol: "tcp"
            port_range_min: 22
            port_range_max: 22
            remote_ip_prefix: "0.0.0.0/0"
    servers:
      - name: "saitou-step"
        key_name: "saitou"
        flavor: "m1.small"
        image: "CentOS7"
        secgroups:
          - "handson_1214_base"
        nics:
          - net-name: "int-net_1214"
        auto_ip: "yes"

  tasks:
    - name: create security group
      os_security_group:
        state=present
        name="{{ item.name }}"
        description="{{ item.desc}}"
      with_items: secgroups
    - name: add rules to secgroup
      os_security_group_rule:
        state=present
        security_group="{{ item[0].name }}"
        protocol="{{ item[1].protocol }}"
        port_range_min="{{ item[1].port_range_min }}"
        port_range_max="{{ item[1].port_range_max }}"
        remote_ip_prefix="{{ item[1].remote_ip_prefix }}"
      with_subelements:
        - secgroups
        - rules
    - name: create servers
      os_server:
        state: present
        timeout: 200
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_username }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project_name }}"
        name: "{{ item.name }}"
        key_name: "{{ item.key_name }}"
        flavor: "{{ item.flavor }}"
        image: "{{ item.image }}"
        security_groups: "{{ item.secgroups }}"
        nics: "{{ item.nics }}"
        auto_ip: yes
      with_items: servers

#
# [EOF]
#
